- hosts: centos7
  tasks:
    - name: Install services
      yum:
        name:
          [
            "nginx",
            "mariadb-server",
            "php",
            "php-mysql",
            "php-fpm",
            "firewalld",
          ]
        state: latest
    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled
    - name: Ensure services enabled and started
      systemd:
        name: "{{item}}"
        state: started
        enabled: true
      with_items:
        - mariadb
        - nginx
    - name: Setup FirewallD rules
      firewalld:
        permanent: yes
        immediate: yes
        service: "{{ item }}"
        state: enabled
      with_items:
        - http
        - https
    - name: Install php-gd and rsync
      yum:
        name: ["php-gd", "rsync"]
    - name: Copy index.html to hosts
      copy:
        src: startup_page/index.html
        dest: /var/www/html

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

- hosts: ubuntu
  tasks:
    - name: Install services
      apt:
        name:
          [
            "nginx",
            "mariadb-server",
            "php",
            "php-mysql",
            "php-fpm",
            "firewalld",
          ]
        state: latest
    - name: Stop Apache2 service
      service:
        name: apache2
        state: stopped
    - name: Ensure services enabled and started
      systemd:
        name: "{{item}}"
        state: started
        enabled: true
      with_items:
        - mariadb
        - nginx
    - name: FirewallD rules
      firewalld:
        permanent: yes
        immediate: yes
        service: "{{ item }}"
        state: enabled
      with_items:
        - http
        - https
    - name: Install php-gd and rsync
      yum:
        name: ["php-gd", "rsync"]
    - name: Copy index.html to hosts
      copy:
        src: startup_page/index.html
        dest: /var/www/html

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
