- hosts: centos7
  vars:

  tasks:
    - name: Install services
      yum:
        name: "{{item}}"
        state: latest
      with_items:
        - nginx
        - mariadb
        - mariadb-server
        - php
        - php-mysql
        - php-fpm
    - name: Ensure services enabled and started
      systemd:
        name: "{{item}}"
        state: started
        enabled: true
      with_items:
        - mariadb
        - nginx
    - name: Setup FirewallD rules
      firewalld:
        permanent: yes
        immediate: yes
        service: "{{ item }}"
        state: enabled
      with_items:
        - http
        - https
    - name: Install php-gd and rsync
      yum:
        name: "{{item}}"
      with_items:
        - php-gd
        - rsync
    - name: Sets Nginx conf file
      template:
        src: "files/nginx.conf.j2"
        dest: "/etc/nginx/sites-available/{{ http_conf }}"
    - name: Enables new site
      file:
        src: "/etc/nginx/sites-available/{{ http_conf }}"
        dest: "/etc/nginx/sites-enabled/{{ http_conf }}"
        state: link
      notify: Reload Nginx
    - name: Removes "default" site
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent
      notify: Reload Nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

- hosts: ubuntu
  vars:

  tasks:
    - name: Install LEMP
      apt:
        name: "{{item}}"
        state: latest
      with_items:
        - nginx
        - mariadb-server
        - php
        - php-mysql
        - php-fpm
        - firewalld
    - name: Remove nginx default site
      shell: fuser -k 80/tcp
      args:
        warn: false
    - name: Ensure services enabled and started
      systemd:
        name: "{{item}}"
        state: started
        enabled: true
      with_items:
        - mariadb
        - nginx
    - name: FirewallD rules
      firewalld:
        permanent: yes
        immediate: yes
        service: "{{ item }}"
        state: enabled
      with_items:
        - http
        - https
    - name: Install php-gd and rsync
      yum:
        name: "{{item}}"
      with_items:
        - php-gd
        - rsync
    - name: Sets Nginx conf file
      template:
        src: "files/nginx.conf.j2"
        dest: "/etc/nginx/sites-available/{{ http_conf }}"
    - name: Enables new site
      file:
        src: "/etc/nginx/sites-available/{{ http_conf }}"
        dest: "/etc/nginx/sites-enabled/{{ http_conf }}"
        state: link
      notify: Reload Nginx
    - name: Removes "default" site
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent
      notify: Reload Nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
