- hosts: centos7
  remote_user: root
  vars:

  tasks:
    - name: Install services
      yum:
        name: "{{item}}"
        state: latest
      with_items:
        - nginx
        - php
        - php-mysql
        - php-fpm
    - name: Install MySQL repo
      yum:
        name: http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm
        state: latest
    - name: Install MySQL
      yum:
        name: "{{item}}"
        state: latest
      with_items:
        - mysql-community-server
        - MySQL-python
    - name: Ensure services enabled and started
      systemd:
        name: "{{item}}"
        state: started
        enabled: true
      with_items:
        - mariadb
        - nginx
    - name: Setup FirewallD rules
      firewalld:
        permanent: yes
        immediate: yes
        service: "{{ item }}"
        state: enabled
      with_items:
        - http
        - https
    - name: Install php-gd and rsync
      yum:
        name: "{{item}}"
      with_items:
        - php-gd
        - rsync

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

- hosts: ubuntu
  remote_user: ubuntu
  vars:

  tasks:
    - name: Install LEMP
      apt:
        name: "{{item}}"
        state: latest
      with_items:
        - nginx
        - mysql-server
        - python3-pymysql
        - php
        - php-mysql
        - php-fpm
    - name: Ensure services enabled and started
      systemd:
        name: "{{item}}"
        state: started
        enabled: true
      with_items:
        - mariadb
        - nginx
    - name: FirewallD rules
      firewalld:
        permanent: yes
        immediate: yes
        service: "{{ item }}"
        state: enabled
      with_items:
        - http
        - https
    - name: Cai dat php-gd, rsync
      yum:
        name: "{{item}}"
      with_items:
        - php-gd
        - rsync

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
